/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BuildPartService } from "../buildPart.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BuildPartCreateInput } from "./BuildPartCreateInput";
import { BuildPart } from "./BuildPart";
import { BuildPartFindManyArgs } from "./BuildPartFindManyArgs";
import { BuildPartWhereUniqueInput } from "./BuildPartWhereUniqueInput";
import { BuildPartUpdateInput } from "./BuildPartUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BuildPartControllerBase {
  constructor(
    protected readonly service: BuildPartService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BuildPart })
  @nestAccessControl.UseRoles({
    resource: "BuildPart",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBuildPart(
    @common.Body() data: BuildPartCreateInput
  ): Promise<BuildPart> {
    return await this.service.createBuildPart({
      data: {
        ...data,

        build: data.build
          ? {
              connect: data.build,
            }
          : undefined,

        product: data.product
          ? {
              connect: data.product,
            }
          : undefined,
      },
      select: {
        build: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BuildPart] })
  @ApiNestedQuery(BuildPartFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BuildPart",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async buildParts(@common.Req() request: Request): Promise<BuildPart[]> {
    const args = plainToClass(BuildPartFindManyArgs, request.query);
    return this.service.buildParts({
      ...args,
      select: {
        build: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BuildPart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BuildPart",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async buildPart(
    @common.Param() params: BuildPartWhereUniqueInput
  ): Promise<BuildPart | null> {
    const result = await this.service.buildPart({
      where: params,
      select: {
        build: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BuildPart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BuildPart",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBuildPart(
    @common.Param() params: BuildPartWhereUniqueInput,
    @common.Body() data: BuildPartUpdateInput
  ): Promise<BuildPart | null> {
    try {
      return await this.service.updateBuildPart({
        where: params,
        data: {
          ...data,

          build: data.build
            ? {
                connect: data.build,
              }
            : undefined,

          product: data.product
            ? {
                connect: data.product,
              }
            : undefined,
        },
        select: {
          build: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BuildPart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BuildPart",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBuildPart(
    @common.Param() params: BuildPartWhereUniqueInput
  ): Promise<BuildPart | null> {
    try {
      return await this.service.deleteBuildPart({
        where: params,
        select: {
          build: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          product: {
            select: {
              id: true,
            },
          },

          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
